on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: Should perform as a dry run

jobs:
  release_new_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          semantic_version: 19.0.5
          dry_run: false
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog@6.0.0
            @semantic-release/github
            @semantic-release/npm
            @semantic-release/git

      - name: Do something when a new release published
        if: steps.semantic_release.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic_release.outputs.new_release_version }}
          echo ${{ steps.semantic_release.outputs.new_release_major_version }}
          echo ${{ steps.semantic_release.outputs.new_release_minor_version }}
          echo ${{ steps.semantic_release.outputs.new_release_patch_version }}
